### ISSUE TITLE
wishbone installation on windows

### ISSUE THREAD

**Issue by YananaLi** [smetj/wishbone#12]
I want to install wishbone on Windows10 system, but it gave me the "ModuleNotFoundError: No module named 'resource' ", and 'resource' is an Unix Specific Service, so how should I fix this issue?

**Comment by smetj** [comment]
Hi @yanali1214 
I'm afraid I have developed Wishbone only with Linux support in mind.
I realize now this is not mentioned in the docs nor the package classifiers (https://github.com/smetj/wishbone/blob/master/setup.py#L91) 

I'll update those to include that prerequisite. Sorry for the inconvenience.
Jelle
